#!/bin/sh


. /lib/lsb/init-functions

BIN_FILE=$(pidof "inotifywait")

case "$1" in
   start)
      log_info_msg "Starting voogle spider..."
      start_daemon /media/Websites/voogle/new-scripts/searchengine.sh
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping voogle spider..."
	kill -9 $(pidof inotifywait)
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
	pidof inotifywait
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

